# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.17.dev0+g54f6163.d20230216'
__version_tuple__ = version_tuple = (0, 0, 17, 'dev0', 'g54f6163.d20230216')
